### ISSUE TITLE
url 변경으로 v0.0.6 업데이트 후 오류가 발생됩니다.

### ISSUE THREAD

**Issue by kyun78** [slasherLee/homebridge-airkorea#5]
좋은 플러그인 만들어주셔서 잘 사용하였습니다..
이번 url 변경으로 사용 못하고 있었습니다..
기존 v0.0.5  사용중 v0.0.6 업데이트 후  아래와 같은 오류가 발생되네요...
뭔가 잘못 된건걸까요.. 문의드립니다.

[6/1/2021, 2:24:13 PM] TypeError: Cannot read property 'dataTime' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-airkorea/index.js:96:63)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-airkorea/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-airkorea/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-airkorea/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by slasherLee** [comment]
v0.0.5는 정부 open api 지원 변경으로 더이상 동작이 안되는것으로 알고 있습니다. 0.0.6부터는 새로운 url로 동작하는데,  혹시 변경된 사이트에 재사용신청은 이미 하셨나요?

**Comment by kyun78** [comment]
사이트에 재사용신청 했습니다만.~~ 다시 한번 확인 해 보겠습니다.
감사합니다.^^

**Comment by kyun78** [comment]
제가 있는지역기 통신장애라고 나오네요...
다른 지역으로 하니 정보 잘 가져 옵니다. 감사합니다...

![image](https://user-images.githubusercontent.com/75590960/120288377-1a5fd500-c2fb-11eb-8aeb-8e9d33d5eeed.png)

홈브린지 플러그인에선 검색이 안되든데 업데이트 전인가 봅니다.~~~

덕분에 좋은 자료 잘 사용하네요..   감사드립니다.^^%

**Comment by slasherLee** [comment]
제가 npm 업데이트를 깜빡했네요. 버젼 업데이트해두었습니다.

**Comment by kyun78** [comment]
감사합니다.^^% 잘 쓰겠습니다....
